-- SQLite script

DROP TABLE IF EXISTS THINGS;
DROP TABLE IF EXISTS BOOKINGS;

CREATE TABLE THINGS (
    ID                  INTEGER         PRIMARY KEY,
    NAME                VARCHAR(600)    NOT NULL,
    DESCRIPTION         VARCHAR(2000),
    KEEPER_NAME         VARCHAR(100),
    KEEPER_PHONE_NUMBER VARCHAR(15),
    KEEPER_ROOM         VARCHAR(100)
);

CREATE TABLE BOOKINGS (
    ID                  INTEGER         PRIMARY KEY,
    ID_THING            INTEGER         NOT NULL,
    BOOKING_START       TIMESTAMP       NOT NULL,
    BOOKING_FINISH      TIMESTAMP       NOT NULL,
    WHO_BOOKED          VARCHAR(100)    NOT NULL,
    FOREIGN KEY(ID_THING) REFERENCES THINGS(ID)
);

INSERT INTO THINGS(ID, NAME, DESCRIPTION, KEEPER_NAME, KEEPER_PHONE_NUMBER, KEEPER_ROOM) VALUES (NULL, 'Stół do tenisa stołowego', 'Stół na 1. piętrze w budynku G', 'Jan Kowalski', '123 456 789', 'G-1-1');
INSERT INTO THINGS(ID, NAME, DESCRIPTION, KEEPER_NAME, KEEPER_PHONE_NUMBER, KEEPER_ROOM) VALUES (NULL, 'Rzutnik cyfrowy', 'Rzutnik o rozdzielczości Full HD', 'Jan Kowalski', '123 456 789', 'G-1-1');
INSERT INTO THINGS(ID, NAME, DESCRIPTION, KEEPER_NAME, KEEPER_PHONE_NUMBER, KEEPER_ROOM) VALUES (NULL, 'Sala G-1-09', 'Sala komputerowa z 20-ma stanowiskami', NULL, NULL, NULL);

INSERT INTO BOOKINGS(ID, ID_THING, BOOKING_START, BOOKING_FINISH, WHO_BOOKED) VALUES (NULL, 1, '2024-03-18 11:00:00', '2024-03-18 12:00:00', 'Anna Nowak');
INSERT INTO BOOKINGS(ID, ID_THING, BOOKING_START, BOOKING_FINISH, WHO_BOOKED) VALUES (NULL, 1, '2024-03-20 13:00:00', '2024-03-20 16:00:00', 'Anna Nowak');
INSERT INTO BOOKINGS(ID, ID_THING, BOOKING_START, BOOKING_FINISH, WHO_BOOKED) VALUES (NULL, 2, '2024-03-19 08:00:00', '2024-03-19 12:00:00', 'Anna Nowak');
INSERT INTO BOOKINGS(ID, ID_THING, BOOKING_START, BOOKING_FINISH, WHO_BOOKED) VALUES (NULL, 2, '2024-04-01 08:00:00', '2024-04-01 12:00:00', 'Anna Nowak');
